iam.biz.idv.validateDocument.billingCustomerManagementMatch.rule: "{"retail": "T(com.ericsson.nsi.csf.iam.v2.identityverification.util.IdentityVerificationUtil).compareValueWithSpel((#doc['DQL_Final_FirstName_Result']?:'') + (#doc['DQL_Final_MiddleName_Result']?:'') + (#doc['DQL_Final_Surname_Result']?:''), #ban['billingAccount']['billingAccountName'])", "care": "T(com.ericsson.nsi.csf.iam.v2.identityverification.util.IdentityVerificationUtil).compareValueWithSpel(#doc['DQL_Final_AddressState_Result'], #ban['billingAddress']['stateOrProvince']) && T(com.ericsson.nsi.csf.iam.v2.identityverification.util.IdentityVerificationUtil).compareValueWithSpel(#doc['DQL_Final_AddressCity_Result'], #ban['billingAddress']['cityName']) && T(com.ericsson.nsi.csf.iam.v2.identityverification.util.IdentityVerificationUtil).compareValueWithSpel(#doc['DQL_Final_AddressPostalCode_Result'], #ban['billingAddress']['postalCode'])","retail_hawaii": "T(com.ericsson.nsi.csf.iam.v2.identityverification.util.IdentityVerificationUtil).compareValueWithSpel((#doc['DQL_Final_FirstName_Result']?:'') + (#doc['DQL_Final_MiddleName_Result']?:'') + (#doc['DQL_Final_Surname_Result']?:''), #ban['billingAccount']['billingAccountName'])"}"
iam.env.airapi.unEnrollFace.url: 'https://developer.catfishair.co/AirApi/2.0/UnEnrollFace'
iam.biz.token.apigee.billingCustomerManagement.version: 'v1'
iam.env.airapi.authenticate.document.url: 'https://developer.catfishair.co/AirApi/2.0/AuthenticateDocument'
iam.biz.idv.submitDocument.airapi.additionalHeaders: 'AC'
iam.env.asserver.basic.authentication: 'CARMNx28at2Tkv1wLsN870tewOwOANGDikTCSlWXzjEf2Q'
iam.biz.idv.deleteDocument.searchDeleteRole.threadPoolMaxSize: '2'
datasource.oracle.minimumIdle: '5'
iam.env.pm.delete.profile.url: 'http://tmo-iam-ca-pm:8080/profile_management/v1/user/profile'
iam.biz.idv.validateDocument.billingCustomerManagementMatch.errorLoggingSpel: "{"retail": "#doc['DQL_Final_FirstName_Result']+'|'+#doc['DQL_Final_MiddleName_Result']+'|'+#doc['DQL_Final_Surname_Result']+'|'+#ban['billingAccount']['billingAccountName']","care": "#doc['DQL_Final_AddressState_Result']+'|'+#ban['billingAddress']['stateOrProvince']+'|'+#doc['DQL_Final_AddressCity_Result']+'|'+#ban['billingAddress']['cityName']+'|'+#doc['DQL_Final_AddressPostalCode_Result']+'|'+#ban['billingAddress']['postalCode']", "retail_hawaii": "#doc['DQL_Final_FirstName_Result']+'|'+#doc['DQL_Final_MiddleName_Result']+'|'+#doc['DQL_Final_Surname_Result']+'|'+#ban['billingAccount']['billingAccountName']"}"
iam.env.provisioning.queryByContract.url: 'http://tmo-iam-ca-provisioning-internal:8080/iam_provisioning/v1/contract'
iam.env.idv.purge.url: 'http://tmo-iam-ca-idv:9114/identityVerification/v1/document/purge'
datasource.oracle.username: 'gitlab_ci'
datasource.oracle.password: 'gitlab_ci'
iam.biz.IdentityVerification.tokenValidation.incapClientIP.check.enable: 'False'
datasource.oracle.maximumPoolSize: '20'
iam.biz.token.apigee.azureBiometrics.version: 'v1'
iam.env.role.create.role.url: 'http://tmo-iam-ca-organization:8080/iam_role/v1/roles'
iam.notification.default.language: 'en_US'
iam.biz.token.apigee.authenticateDocument.partnerId: 'authentic-id'
iam.env.airapi.enrollFace.url: 'https://developer.catfishair.co/AirApi/2.0/EnrollFace'
iam.env.airapi.authenticate.face.url: 'https://developer.catfishair.co/AirApi/2.0/AuthenticateFace'
iam.env.toece.basic.authentication: 'CATu8P6TDZEEGKPaC3STT3W9Ei8w7WZ8/o'
iam.biz.token.apigee.azureBiometrics.partnerId: 'BiometricController'
iam.biz.idv.validatePortrait.airapi.additionalHeaders: 'AC,transactionInformation'
datasource.oracle.jdbcUrl: 'jdbc:oracle:thin:@127.0.0.1:1521:msdp'
iam.biz.token.apigee.authenticateDocument.version: 'v1'
iam.biz.azure.biometrics.enable: 'False'
iam.biz.idv.submitDocument.selfieBase64.charsetName: 'UTF-8'
iam.role.query.url: 'http://tmo-iam-ca-organization:8080/iam_role/v1/roles/search/internal'
iam.endpoint.adp.certificate.path: '/etc/cgc-iam-service.d/config/iam-service/tmo-iam-ca-adp-trusted-certificate.pem'
iam.endpoint.ssl.keystore.path: '/etc/cgc-iam-service.d/config/iam-service/tmo-iam-ca-adp-trusted-certificate.jks'
iam.env.airapi.matchSelfie.url: 'https://developer.catfishair.co/AirApi/2.0/MatchSelfie'
iam.endpoint.ssl.keystore.password: 'password'
iam.biz.idv.validateDocument.channelMatch.fieldsMapping: 'given_name:DQL_Final_FirstName_Result,family_name:DQL_Final_Surname_Result,document_number:DQL_Final_DocumentNumber_Result,birthdate:DQL_Final_BirthDate_Result,issuer:DQL_Final_IssuerCode_Result,expiration_date:DQL_Final_ExpirationDate_Result'
iam.biz.idv.validateDocument.filterCharacters: '[\, ._]'
iam.env.tocac.basic.authentication: 'CATTzEJXmUBtHEGv1Ygkbb8yClz/OHPl9Z4RIflGVuSu+g'
iam.biz.validate.document.mandatory.scopes: 'docAuth'
iam.env.role.delete.role.url: 'http://tmo-iam-ca-organization:8080/iam_role/v1/roles/${iam_role_id}'
iam.env.ets.generatePopToken.url: 'http://tmo-iam-ca-ets:8080/external_token_service/v1/pop'
iam.env.provisioning.queryByBillingAccount.url: 'http://tmo-iam-ca-provisioning-internal:8080/iam_provisioning/v1/billingCode'
iam.biz.idv.validatePortrait.actionCodeToError.mapping: '60:authentication_failure'
iam.env.idv.deleteGovernment.url: 'http://tmo-iam-ca-idv:8080/identityVerification/v1/document'
iam.biz.idv.initDocument.collectUserIdProcessDelayedInDay: '7'
iam.biz.idv.submitDocument.imgAverageSizeInMb: '5'
iam.env.service.gracefulShutDown.enabled: 'True'
iam.ece.logUserSecurityEvent.url: 'http://eric-idm-rba-user-act:8080/useractivity/v1/usersecurityevent'
iam.env.toece.trustedbasic.authentication: 'CAT6OtnaNN/CDMZT5ZdvkNGdC2z3ib9tPeydzH9e8SkvU70gcF6TuHYA+j5OzQ8VVzRZ4kgnqgHIbQIr+kTHtz0X'
iam.biz.token.apigee.billingCustomerManagement.partnerId: 'billingCustomerManagement'
iam.env.idv.finishRegistration.url: 'http://tmo-iam-ca-idv:8080/identityVerification/v1/document/finish'
iam.biz.idv.validateDocument.channelMatch.rule: '{"retail":[["given_name"\,"family_name"\,"document_number"\,"birthdate"]]\,"digital":[["given_name"\,"family_name"\,"birthdate"]\, ["family_name"\,"document_number"\,"issuer"]]\,"retail_hawaii":[["given_name"\,"family_name"\,"document_number"\,"expiration_date"]]}'
iam.env.billingCustomerManagement.url: 'https://ip:port/retrieve-billing-account'
iam.biz.idv.finishDocument.cleanupDocument.maxRecord: '50'
iam.env.service.gracefulShutDown.timeoutInSecond: '60'
iam.env.azure.biometrics.url: 'http://ip:port/biometrics/v1'
iam.biz.idv.validateDocument.simpleValidation.channels: 'retail'
iam.biz.idv.deleteDocument.searchDeleteRole.threadPoolCoreSize: '2'
iam.biz.dps.userIdAggregation.enableApiNames: 'FINISH_ID_REGISTRATION,unEnrollFace'
iam.env.airapi.update.transaction.url: 'https://developer.catfishair.co/AirApi/2.0/UpdateTransaction'